OUTPUT_DIR: "./exps/prw_1_1"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "/media/sda/datasets/ReID/PRW/PRW-v16.04.20"
  BATCH_SIZE_TRAIN: 4
SOLVER:
  MAX_EPOCHS: 20
  BASE_LR: 0.003
MODEL:
  LOSS:
    TYPE: 'OIM'
    OIM_EPS: 0.1
    LUT_SIZE: 482
    CQ_SIZE: 500
NVIDIA_DEVICE: 0
EVAL_PERIOD: 2
CKPT_PERIOD: 1
