OUTPUT_DIR: "./exps/cuhk_oim-3corr3"
INPUT:
  DATASET: "CUHK-SYSU"
  DATA_ROOT: "/media/data/lzj/dataset/cuhk_sysu"
  BATCH_SIZE_TRAIN: 3
SOLVER:
  MAX_EPOCHS: 20
  BASE_LR: 0.003
  LW_RCNN_SOFTMAX_2ND: 0.1
  LW_RCNN_SOFTMAX_3RD: 0.1
MODEL:
  LOSS:
    TYPE: 'OIM'
    OIM_EPS: 0.1
    LUT_SIZE: 5532
    CQ_SIZE: 5000
  # ROI_HEAD:
    # NORM_TYPE: 'protonorm'
NVIDIA_DEVICE:  1
DISP_PERIOD: 100
EVAL_PERIOD: 1
CKPT_PERIOD: 1
EVAL_GALLERY_SIZE: 100
